version: '3'

services:
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: django-container
    entrypoint: sh -c './start.sh'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    
volumes:
  pgdata: