FROM python:3.10

ENV PYTHONUNBUFFERED 1

RUN mkdir /code /var/log/library

WORKDIR /code

ADD requirements/requirements.txt /code/

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code/

RUN chmod +x *.sh

CMD ["sh", "/code/start.sh"]

